---
all:
  children:
    pemserver:
      hosts:
        pemserver1.tower.internal:
          ansible_host: 3.214.143.70
          private_ip: 10.0.0.11
    barmanserver:
      hosts:
        barmanserver1.tower.internal:
          ansible_host: 44.192.106.243
          private_ip: 10.0.0.141
          pem_agent: true
          pem_server_private_ip: 10.0.0.11
    primary:
      hosts:
        epas1.tower.internal:
          ansible_host: 3.227.243.103
          private_ip: 10.0.0.125
          barman: true
          barman_server_private_ip: 10.0.0.141
          barman_backup_method: postgres
          pem_agent: true
          pem_server_private_ip: 10.0.0.11
