---
all:
  children:
    pemserver:
      hosts:
        pemserver1.vincent.internal:
          ansible_host: 35.231.170.206
          private_ip: 10.142.0.3
    barmanserver:
      hosts:
        barmanserver1.vincent.internal:
          ansible_host: 34.75.241.77
          private_ip: 10.142.0.2
    primary:
      hosts:
        epas1.vincent.internal:
          ansible_host: 34.73.136.44
          private_ip: 10.142.0.4
          barman: true
          barman_server_private_ip: 10.142.0.2
          barman_backup_method: postgres
          pem_agent: true
          pem_server_private_ip: 10.142.0.3
