---
all:
  children:
    pemserver:
      hosts:
        pemserver1.tower2.internal:
          ansible_host: 44.198.171.111
          private_ip: 10.0.0.171
    barmanserver:
      hosts:
        barmanserver1.tower2.internal:
          ansible_host: 34.232.48.126
          private_ip: 10.0.0.197
          pem_agent: true
          pem_server_private_ip: 10.0.0.171
    primary:
      hosts:
        epas1.tower2.internal:
          ansible_host: 3.235.163.78
          private_ip: 10.0.0.109
          barman: true
          barman_server_private_ip: 10.0.0.197
          barman_backup_method: postgres
          pem_agent: true
          pem_server_private_ip: 10.0.0.171
    standby:
      hosts:
        epas2.tower2.internal:
          ansible_host: 34.203.36.140
          private_ip: 10.0.2.203
          barman: true
          barman_server_private_ip: 10.0.0.197
          barman_backup_method: postgres
          replication_type: synchronous
          upstream_node_private_ip: 10.0.0.109
          pem_agent: true
          pem_server_private_ip: 10.0.0.171
        epas3.tower2.internal:
          ansible_host: 54.205.34.124
          private_ip: 10.0.1.110
          barman: true
          barman_server_private_ip: 10.0.0.197
          barman_backup_method: postgres
          replication_type: asynchronous
          upstream_node_private_ip: 10.0.0.109
          pem_agent: true
          pem_server_private_ip: 10.0.0.171
