---
all:
  children:
    pemserver:
      hosts:
        pemserver1.tower.internal:
          ansible_host: 54.236.73.203
          private_ip: 10.0.0.123
    barmanserver:
      hosts:
        barmanserver1.tower.internal:
          ansible_host: 3.237.234.215
          private_ip: 10.0.0.204
          pem_agent: true
          pem_server_private_ip: 10.0.0.123
    primary:
      hosts:
        epas1.tower.internal:
          ansible_host: 3.221.170.16
          private_ip: 10.0.0.209
          barman: true
          barman_server_private_ip: 10.0.0.204
          barman_backup_method: postgres
          pem_agent: true
          pem_server_private_ip: 10.0.0.123
