---
all:
  children:
    pemserver:
      hosts:
        pemserver1.tower.internal:
          ansible_host: 3.236.130.252
          private_ip: 10.0.0.84
    barmanserver:
      hosts:
        barmanserver1.tower.internal:
          ansible_host: 44.193.3.43
          private_ip: 10.0.0.160
          pem_agent: true
          pem_server_private_ip: 10.0.0.84
    primary:
      hosts:
        epas1.tower.internal:
          ansible_host: 44.192.100.78
          private_ip: 10.0.0.248
          barman: true
          barman_server_private_ip: 10.0.0.160
          barman_backup_method: postgres
          pem_agent: true
          pem_server_private_ip: 10.0.0.84
