---
all:
  children:
    pemserver:
      hosts:
        pemserver1.test.internal:
          ansible_host: 3.238.93.58
          private_ip: 10.0.0.154
    barmanserver:
      hosts:
        barmanserver1.test.internal:
          ansible_host: 3.80.173.15
          private_ip: 10.0.0.115
          pem_agent: true
          pem_server_private_ip: 10.0.0.154
    dbt2_client:
      hosts:
        dbt2_client1.test.internal:
          ansible_host: 3.236.155.153
          private_ip: 10.0.0.207
    dbt2_driver:
      hosts:
        dbt2_driver1.test.internal:
          ansible_host: 3.239.14.112
          private_ip: 10.0.0.71
    primary:
      hosts:
        epas1.test.internal:
          ansible_host: 44.198.180.37
          private_ip: 10.0.0.219
          barman: true
          barman_server_private_ip: 10.0.0.115
          barman_backup_method: postgres
          pem_agent: true
          pem_server_private_ip: 10.0.0.154
