---
all:
  children:
    pemserver:
      hosts:
        pemserver1.vincent.internal:
          ansible_host: 34.139.180.171
          private_ip: 10.142.0.4
    barmanserver:
      hosts:
        barmanserver1.vincent.internal:
          ansible_host: 34.138.188.134
          private_ip: 10.142.0.3
    primary:
      hosts:
        epas1.vincent.internal:
          ansible_host: 35.243.209.225
          private_ip: 10.142.0.2
          barman: true
          barman_server_private_ip: 10.142.0.3
          barman_backup_method: postgres
          pem_agent: true
          pem_server_private_ip: 10.142.0.4
