---
all:
  children:
    pemserver:
      hosts:
        pemserver1.test.internal:
          ansible_host: 3.239.108.226
          private_ip: 10.0.0.25
    barmanserver:
      hosts:
        barmanserver1.test.internal:
          ansible_host: 3.238.159.93
          private_ip: 10.0.0.94
          pem_agent: true
          pem_server_private_ip: 10.0.0.25
    dbt2_client:
      hosts:
        dbt2_client1.test.internal:
          ansible_host: 3.235.152.139
          private_ip: 10.0.0.189
    dbt2_driver:
      hosts:
        dbt2_driver1.test.internal:
          ansible_host: 3.235.109.157
          private_ip: 10.0.0.240
    primary:
      hosts:
        epas1.test.internal:
          ansible_host: 100.25.44.85
          private_ip: 10.0.0.102
          barman: true
          barman_server_private_ip: 10.0.0.94
          barman_backup_method: postgres
          pem_agent: true
          pem_server_private_ip: 10.0.0.25
