---
all:
  children:
    pemserver:
      hosts:
        pemserver1.tower.internal:
          ansible_host: 44.192.131.9
          private_ip: 10.0.0.173
    barmanserver:
      hosts:
        barmanserver1.tower.internal:
          ansible_host: 3.91.45.145
          private_ip: 10.0.0.215
          pem_agent: true
          pem_server_private_ip: 10.0.0.173
    primary:
      hosts:
        epas1.tower.internal:
          ansible_host: 54.85.90.208
          private_ip: 10.0.0.223
          barman: true
          barman_server_private_ip: 10.0.0.215
          barman_backup_method: postgres
          pem_agent: true
          pem_server_private_ip: 10.0.0.173
