---
all:
  children:
    pemserver:
      hosts:
        pemserver1.tower3.internal:
          ansible_host: 54.234.118.155
          private_ip: 10.0.2.225
    barmanserver:
      hosts:
        barmanserver1.tower3.internal:
          ansible_host: 54.235.50.245
          private_ip: 10.0.2.113
          pem_agent: true
          pem_server_private_ip: 10.0.2.225
    primary:
      hosts:
        epas1.tower3.internal:
          ansible_host: 54.145.41.55
          private_ip: 10.0.2.100
          barman: true
          barman_server_private_ip: 10.0.2.113
          barman_backup_method: postgres
          pem_agent: true
          pem_server_private_ip: 10.0.2.225
    standby:
      hosts:
        epas2.tower3.internal:
          ansible_host: 3.237.69.210
          private_ip: 10.0.0.252
          barman: true
          barman_server_private_ip: 10.0.2.113
          barman_backup_method: postgres
          replication_type: synchronous
          upstream_node_private_ip: 10.0.2.100
          pem_agent: true
          pem_server_private_ip: 10.0.2.225
        epas3.tower3.internal:
          ansible_host: 54.210.91.0
          private_ip: 10.0.1.228
          barman: true
          barman_server_private_ip: 10.0.2.113
          barman_backup_method: postgres
          replication_type: asynchronous
          upstream_node_private_ip: 10.0.2.100
          pem_agent: true
          pem_server_private_ip: 10.0.2.225
    pgpool2:
      hosts:
        pgpool21.tower3.internal:
          ansible_host: 3.91.44.26
          private_ip: 10.0.2.143
          primary_private_ip: 10.0.2.100
          pem_agent: true
          pem_server_private_ip: 10.0.2.225
        pgpool22.tower3.internal:
          ansible_host: 54.226.96.15
          private_ip: 10.0.0.251
          primary_private_ip: 10.0.2.100
          pem_agent: true
          pem_server_private_ip: 10.0.2.225
        pgpool23.tower3.internal:
          ansible_host: 54.82.162.248
          private_ip: 10.0.1.78
          primary_private_ip: 10.0.2.100
          pem_agent: true
          pem_server_private_ip: 10.0.2.225
