---
all:
  children:
    pemserver:
      hosts:
        pemserver1.tower.internal:
          ansible_host: 3.219.47.140
          private_ip: 10.0.0.150
    barmanserver:
      hosts:
        barmanserver1.tower.internal:
          ansible_host: 3.216.95.219
          private_ip: 10.0.0.250
          pem_agent: true
          pem_server_private_ip: 10.0.0.150
    primary:
      hosts:
        epas1.tower.internal:
          ansible_host: 44.197.188.208
          private_ip: 10.0.0.128
          barman: true
          barman_server_private_ip: 10.0.0.250
          barman_backup_method: postgres
          pem_agent: true
          pem_server_private_ip: 10.0.0.150
